# Generated by Django 5.2.1 on 2025-05-19 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_book_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='available_copies',
            field=models.PositiveIntegerField(blank=True, default=models.PositiveIntegerField(), null=True),
        ),
    ]
